name: issue.yaml

on:
  issues: # issue_comment: # c'est seulement pour quand un commentaire est créé...
    types: [opened] # [created]

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: validation
        run: echo "Issue créé correctement"

