name: next_workflow.yaml

on:
  workflow_run:
    workflows: [build, test]
    types: [completed]
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm only supposed to launch if the last one worked fine"
