name: next_workflow.yaml

on:
  workflow_run:
    workflows: [Merge PR]
    types: [completed]
jobs:
  follow-up:
    runs-on: ubuntu-latest
    steps:
      - name: message
        run: echo "I'm only supposed to launch if the last one worked fine"
